# First, rename all tables to what Stats 5 uses, too.
RENAME TABLE stats_arrows TO stats_arrows_shot;
RENAME TABLE stats_blocks_broken TO stats_block_break;
RENAME TABLE stats_blocks_placed TO stats_block_place;
RENAME TABLE stats_commands_done TO stats_commands_performed;
RENAME TABLE stats_omnomnom TO stats_food_consumed;
RENAME TABLE stats_joins TO stats_times_joined;
RENAME TABLE stats_last_seen TO stats_last_quit;
RENAME TABLE stats_shears TO stats_times_sheared;
RENAME TABLE stats_trades TO stats_trades_performed;

# Then, drop all keys and indexes before changing any columns
# Generated by
# SELECT CONCAT('ALTER TABLE ', `Table`, ' DROP INDEX ', GROUP_CONCAT(`Index` SEPARATOR ', DROP INDEX '),';' )
# FROM (SELECT table_name AS `Table`, index_name AS `Index`
# FROM information_schema.statistics WHERE table_schema = DATABASE() GROUP BY `Table`, `Index`) AS tmp GROUP BY `Table`;
ALTER TABLE stats_achievements
    DROP INDEX `PRIMARY`;
ALTER TABLE stats_arrows
    DROP INDEX `PRIMARY`,
    DROP INDEX id,
    DROP INDEX uuid;
ALTER TABLE stats_beds_entered
    DROP INDEX id,
    DROP INDEX uuid,
    DROP INDEX `PRIMARY`;
ALTER TABLE stats_blocks_broken
    DROP INDEX `PRIMARY`,
    DROP INDEX id,
    DROP INDEX uuid;
ALTER TABLE stats_blocks_placed
    DROP INDEX id,
    DROP INDEX uuid,
    DROP INDEX `PRIMARY`;
ALTER TABLE stats_buckets_emptied
    DROP INDEX uuid,
    DROP INDEX `PRIMARY`,
    DROP INDEX id;
ALTER TABLE stats_buckets_filled
    DROP INDEX `PRIMARY`,
    DROP INDEX id,
    DROP INDEX uuid;
ALTER TABLE stats_commands_done
    DROP INDEX id,
    DROP INDEX uuid,
    DROP INDEX `PRIMARY`;
ALTER TABLE stats_custom
    DROP INDEX `PRIMARY`,
    DROP INDEX id;
ALTER TABLE stats_damage_taken
    DROP INDEX `PRIMARY`,
    DROP INDEX id,
    DROP INDEX uuid;
ALTER TABLE stats_death
    DROP INDEX id,
    DROP INDEX uuid,
    DROP INDEX `PRIMARY`;
ALTER TABLE stats_eggs_thrown
    DROP INDEX id,
    DROP INDEX uuid,
    DROP INDEX `PRIMARY`;
ALTER TABLE stats_fish_caught
    DROP INDEX `PRIMARY`,
    DROP INDEX id,
    DROP INDEX uuid;
ALTER TABLE stats_items_crafted
    DROP INDEX id,
    DROP INDEX uuid,
    DROP INDEX `PRIMARY`;
ALTER TABLE stats_items_dropped
    DROP INDEX `PRIMARY`,
    DROP INDEX id,
    DROP INDEX uuid;
ALTER TABLE stats_items_picked_up
    DROP INDEX id,
    DROP INDEX uuid,
    DROP INDEX `PRIMARY`;
ALTER TABLE stats_joins
    DROP INDEX uuid,
    DROP INDEX `PRIMARY`,
    DROP INDEX id;
ALTER TABLE stats_kill
    DROP INDEX `PRIMARY`,
    DROP INDEX id,
    DROP INDEX uuid;
ALTER TABLE stats_last_join
    DROP INDEX id,
    DROP INDEX uuid,
    DROP INDEX `PRIMARY`;
ALTER TABLE stats_last_seen
    DROP INDEX `PRIMARY`,
    DROP INDEX id,
    DROP INDEX uuid;
ALTER TABLE stats_locks
    DROP INDEX `PRIMARY`,
    DROP INDEX uuid;
ALTER TABLE stats_money
    DROP INDEX id,
    DROP INDEX uuid,
    DROP INDEX `PRIMARY`;
ALTER TABLE stats_move
    DROP INDEX id,
    DROP INDEX uuid,
    DROP INDEX `PRIMARY`;
ALTER TABLE stats_omnomnom
    DROP INDEX `PRIMARY`,
    DROP INDEX id,
    DROP INDEX uuid;
ALTER TABLE stats_players
    DROP INDEX `PRIMARY`,
    DROP INDEX uuid;
ALTER TABLE stats_playtime
    DROP INDEX id,
    DROP INDEX uuid,
    DROP INDEX `PRIMARY`;
ALTER TABLE stats_pvp
    DROP INDEX `PRIMARY`,
    DROP INDEX id,
    DROP INDEX uuid;
ALTER TABLE stats_pvp_streak
    DROP INDEX id,
    DROP INDEX uuid,
    DROP INDEX `PRIMARY`;
ALTER TABLE stats_pvp_top_streak
    DROP INDEX id,
    DROP INDEX uuid,
    DROP INDEX `PRIMARY`;
ALTER TABLE stats_shears
    DROP INDEX `PRIMARY`,
    DROP INDEX id,
    DROP INDEX uuid;
ALTER TABLE stats_teleports
    DROP INDEX id,
    DROP INDEX uuid,
    DROP INDEX `PRIMARY`;
ALTER TABLE stats_times_changed_world
    DROP INDEX `PRIMARY`,
    DROP INDEX id,
    DROP INDEX uuid;
ALTER TABLE stats_times_kicked
    DROP INDEX id,
    DROP INDEX uuid,
    DROP INDEX `PRIMARY`;
ALTER TABLE stats_tools_broken
    DROP INDEX id,
    DROP INDEX uuid,
    DROP INDEX `PRIMARY`;
ALTER TABLE stats_trades
    DROP INDEX `PRIMARY`,
    DROP INDEX id,
    DROP INDEX uuid;
ALTER TABLE stats_words_said
    DROP INDEX id,
    DROP INDEX uuid,
    DROP INDEX `PRIMARY`;
ALTER TABLE stats_xp_gained
    DROP INDEX `PRIMARY`,
    DROP INDEX id,
    DROP INDEX uuid;

# Generated by
# SELECT concat('ALTER TABLE ', TABLE_NAME, ' DROP FOREIGN KEY ', CONSTRAINT_NAME, ';')
# FROM information_schema.key_column_usage WHERE CONSTRAINT_SCHEMA = DATABASE() AND referenced_table_name IS NOT NULL;
ALTER TABLE stats_arrows
    DROP FOREIGN KEY stats_arrows_ibfk_1;
ALTER TABLE stats_beds_entered
    DROP FOREIGN KEY stats_beds_entered_ibfk_1;
ALTER TABLE stats_blocks_broken
    DROP FOREIGN KEY stats_blocks_broken_ibfk_1;
ALTER TABLE stats_blocks_placed
    DROP FOREIGN KEY stats_blocks_placed_ibfk_1;
ALTER TABLE stats_buckets_emptied
    DROP FOREIGN KEY stats_buckets_emptied_ibfk_1;
ALTER TABLE stats_buckets_filled
    DROP FOREIGN KEY stats_buckets_filled_ibfk_1;
ALTER TABLE stats_commands_done
    DROP FOREIGN KEY stats_commands_done_ibfk_1;
ALTER TABLE stats_damage_taken
    DROP FOREIGN KEY stats_damage_taken_ibfk_1;
ALTER TABLE stats_death
    DROP FOREIGN KEY stats_death_ibfk_1;
ALTER TABLE stats_eggs_thrown
    DROP FOREIGN KEY stats_eggs_thrown_ibfk_1;
ALTER TABLE stats_fish_caught
    DROP FOREIGN KEY stats_fish_caught_ibfk_1;
ALTER TABLE stats_items_crafted
    DROP FOREIGN KEY stats_items_crafted_ibfk_1;
ALTER TABLE stats_items_dropped
    DROP FOREIGN KEY stats_items_dropped_ibfk_1;
ALTER TABLE stats_items_picked_up
    DROP FOREIGN KEY stats_items_picked_up_ibfk_1;
ALTER TABLE stats_joins
    DROP FOREIGN KEY stats_joins_ibfk_1;
ALTER TABLE stats_kill
    DROP FOREIGN KEY stats_kill_ibfk_1;
ALTER TABLE stats_last_join
    DROP FOREIGN KEY stats_last_join_ibfk_1;
ALTER TABLE stats_last_seen
    DROP FOREIGN KEY stats_last_seen_ibfk_1;
ALTER TABLE stats_locks
    DROP FOREIGN KEY stats_locks_ibfk_1;
ALTER TABLE stats_money
    DROP FOREIGN KEY stats_money_ibfk_1;
ALTER TABLE stats_move
    DROP FOREIGN KEY stats_move_ibfk_1;
ALTER TABLE stats_omnomnom
    DROP FOREIGN KEY stats_omnomnom_ibfk_1;
ALTER TABLE stats_playtime
    DROP FOREIGN KEY stats_playtime_ibfk_1;
ALTER TABLE stats_pvp
    DROP FOREIGN KEY stats_pvp_ibfk_1;
ALTER TABLE stats_pvp_streak
    DROP FOREIGN KEY stats_pvp_streak_ibfk_1;
ALTER TABLE stats_pvp_top_streak
    DROP FOREIGN KEY stats_pvp_top_streak_ibfk_1;
ALTER TABLE stats_shears
    DROP FOREIGN KEY stats_shears_ibfk_1;
ALTER TABLE stats_teleports
    DROP FOREIGN KEY stats_teleports_ibfk_1;
ALTER TABLE stats_times_changed_world
    DROP FOREIGN KEY stats_times_changed_world_ibfk_1;
ALTER TABLE stats_times_kicked
    DROP FOREIGN KEY stats_times_kicked_ibfk_1;
ALTER TABLE stats_tools_broken
    DROP FOREIGN KEY stats_tools_broken_ibfk_1;
ALTER TABLE stats_trades
    DROP FOREIGN KEY stats_trades_ibfk_1;
ALTER TABLE stats_words_said
    DROP FOREIGN KEY stats_words_said_ibfk_1;
ALTER TABLE stats_xp_gained
    DROP FOREIGN KEY stats_xp_gained_ibfk_1;

# Prepare the stats_worlds and stats_players tables
ALTER TABLE stats_players
    ADD COLUMN id            INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    CHANGE uuid uuid_old     VARCHAR(255),
    ADD COLUMN uuid          BINARY(16)       NOT NULL,
    CHANGE `name` `username` VARCHAR(16)      NOT NULL DEFAULT 'Unknown';
UPDATE stats_players
SET uuid=UNHEX(REPLACE(uuid_old), '-', '');
ALTER TABLE stats_players
    DROP COLUMN uuid_old;

CREATE TABLE `stats_worlds`
(
    `id`      int(10) unsigned NOT NULL AUTO_INCREMENT,
    `uuid`    binary(16)       NOT NULL,
    `name`    text             NOT NULL,
    `raining` tinyint(1)       NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uuid_UNIQUE` (`uuid`)
);
INSERT IGNORE INTO stats_worlds (uuid)
SELECT DISTINCT(world)
FROM stats_playtime;

# Change all columns for simple tables
ALTER TABLE `stats_arrows_shot`
    ADD COLUMN player_id     INT(10) UNSIGNED NOT NULL,
    ADD COLUMN player_helper BINARY(16),
    ADD COLUMN world_id      INT(10) UNSIGNED NOT NULL,
    CHANGE `value` `amount`  double           NOT NULL,
    ADD COLUMN last_updated  TIMESTAMP        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
UPDATE stats_arrows_shot
SET player_helper=UNHEX(REPLACE(uuid), '-', '');
UPDATE `stats_arrows_shot` a INNER JOIN stats_players b ON a.player_helper = b.uuid
SET a.player_id=b.id;
UPDATE `stats_arrows_shot` a INNER JOIN stats_worlds b ON a.world = b.uuid
SET a.world_id=b.id;
ALTER TABLE `stats_arrows_shot`
    DROP COLUMN player_helper,
    DROP COLUMN id,
    DROP COLUMN uuid,
    DROP COLUMN world,
    ADD PRIMARY KEY (`player_id`, `world_id`),
    ADD KEY `p_id_idx` (`player_id`),
    ADD KEY `w_id_idx` (`world_id`),
    ADD CONSTRAINT `stats_arrows_shot_p_id` FOREIGN KEY (`player_id`) REFERENCES `stats_players` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
    ADD CONSTRAINT `stats_arrows_shot_w_id` FOREIGN KEY (`world_id`) REFERENCES `stats_worlds` (`id`) ON UPDATE CASCADE;


#Not converted:
